<a href="https://colab.research.google.com/github/Piau10/Projetos-Iniciais/blob/main/Exerc_pandas_dnc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

import kagglehub

# Download latest version
path = kagglehub.dataset_download("kaggle/sf-salaries")

print("Path to dataset files:", path)

In [2]:
import pandas as pd

In [10]:
# lendo a base de dados
df = pd.read_csv("/kaggle/input/sf-salaries/Salaries.csv")

/tmp/ipython-input-3973278695.py:1: DtypeWarning: Columns (3,4,5,6,12) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("/kaggle/input/sf-salaries/Salaries.csv")

In [11]:
df

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.0,56120.71,198306.9,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737.0,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148649,148650,Roy I Tillery,Custodian,0.00,0.00,0.00,0.00,0.00,0.00,2014,NaN,San Francisco,PT
148650,148651,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148651,148652,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148652,148653,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.00,-618.13,-618.13,2014,NaN,San Francisco,PT

In [15]:
#mostrando as 5 primeiras linhas da base para entender os dados
df.head(5)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.0,56120.71,198306.9,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737.0,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

In [16]:
#mostra todas as informações
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148654 non-null  int64
 1   EmployeeName      148654 non-null  object
 2   JobTitle          148654 non-null  object
 3   BasePay           148049 non-null  object
 4   OvertimePay       148654 non-null  object
 5   OtherPay          148654 non-null  object
 6   Benefits          112495 non-null  object
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object
 12  Status            38119 non-null   object
dtypes: float64(3), int64(2), object(8)
memory usage: 14.7+ MB

In [17]:
#fazendo a contagem das linhas por colunas
df.count()

Id                  148654
EmployeeName        148654
JobTitle            148654
BasePay             148049
OvertimePay         148654
OtherPay            148654
Benefits            112495
TotalPay            148654
TotalPayBenefits    148654
Year                148654
Notes                    0
Agency              148654
Status               38119
dtype: int64

In [19]:
#lenth quantidade de linhas
len(df)

148654

In [23]:
#lendo a coluna BasePay e nota que ela tem valores como object que precisa ser tratado
#precisamos de valores em float para poder fazer as análises corretas.
df["BasePay"]

0            167411.18
1            155966.02
2            212739.13
3              77916.0
4             134401.6
              ...
148649            0.00
148650    Not Provided
148651    Not Provided
148652    Not Provided
148653            0.00
Name: BasePay, Length: 148654, dtype: object

In [24]:
# valores true é onde são Not provided.
df["BasePay"] == "Not Provided"

0         False
1         False
2         False
3         False
4         False
          ...
148649    False
148650     True
148651     True
148652     True
148653    False
Name: BasePay, Length: 148654, dtype: bool

In [25]:
#agora fazendo uma filtragem condicional
#esses valores fazem com que o pandas trate esses valores como texto, onde devem ser int ou float.
df[df["BasePay"] == "Not Provided"]

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
148646,148647,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.0,0.0,2014,NaN,San Francisco,NaN
148650,148651,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.0,0.0,2014,NaN,San Francisco,NaN
148651,148652,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.0,0.0,2014,NaN,San Francisco,NaN
148652,148653,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.0,0.0,2014,NaN,San Francisco,NaN

In [26]:
#pegando os dados contrários da condição anterior
#observe que adicionamos o ~ seguido de parentêses dentro do código.
df[~(df["BasePay"] == "Not Provided")]

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.0,56120.71,198306.9,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737.0,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148645,148646,Carolyn A Wilson,Human Services Technician,0.00,0.00,0.00,0.00,0.00,0.00,2014,NaN,San Francisco,PT
148647,148648,Joann Anderson,Communications Dispatcher 2,0.00,0.00,0.00,0.00,0.00,0.00,2014,NaN,San Francisco,PT
148648,148649,Leon Walker,Custodian,0.00,0.00,0.00,0.00,0.00,0.00,2014,NaN,San Francisco,PT
148649,148650,Roy I Tillery,Custodian,0.00,0.00,0.00,0.00,0.00,0.00,2014,NaN,San Francisco,PT
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.00,-618.13,-618.13,2014,NaN,San Francisco,PT

In [27]:
# agora colocamos o resultado que queremos dentro do nosso DataFrame.
df = df[~(df["BasePay"] == "Not Provided")]

In [30]:
# não temos mais os valores Not Provided
df["BasePay"]

0         167411.18
1         155966.02
2         212739.13
3           77916.0
4          134401.6
            ...
148645         0.00
148647         0.00
148648         0.00
148649         0.00
148653         0.00
Name: BasePay, Length: 148650, dtype: object

In [32]:
#ainda lê como objeto porque foi mantido a leitura feita no início ('O') de objeto
df["BasePay"].dtype

dtype('O')

In [34]:
# fazendo a conversão para float
df["BasePay"].astype (float)

0         167411.18
1         155966.02
2         212739.13
3          77916.00
4         134401.60
            ...
148645         0.00
148647         0.00
148648         0.00
148649         0.00
148653         0.00
Name: BasePay, Length: 148650, dtype: float64

In [35]:
#modificando essa coluna no DataFrame de object para float
df["BasePay"] = df["BasePay"].astype (float)

/tmp/ipython-input-2559787048.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["BasePay"] = df["BasePay"].astype (float)

In [36]:
df.info(

)

<class 'pandas.core.frame.DataFrame'>
Index: 148650 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148650 non-null  int64
 1   EmployeeName      148650 non-null  object
 2   JobTitle          148650 non-null  object
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  object
 5   OtherPay          148650 non-null  object
 6   Benefits          112491 non-null  object
 7   TotalPay          148650 non-null  float64
 8   TotalPayBenefits  148650 non-null  float64
 9   Year              148650 non-null  int64
 10  Notes             0 non-null       float64
 11  Agency            148650 non-null  object
 12  Status            38119 non-null   object
dtypes: float64(4), int64(2), object(7)
memory usage: 15.9+ MB

In [37]:
# qual o maior valor de hora extra paga (OvertimePay)
#também fazendo a modificação de object para float
df["OvertimePay"].astype(float).max()

245131.88

In [39]:
#podemos criar uma variável para este código que mostra o valor máximo
valor_maximo = df["OvertimePay"].astype(float).max()

In [40]:
#identificando a pessoa que recebeu este valor
df[df["OvertimePay"] == valor_maximo]

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN

In [44]:
# buscando informações pelo nome
# Qual é o cargo de JOSEPH DRISCOLL?
df[df["EmployeeName"] == "JOSEPH DRISCOLL"] ["JobTitle"]

#se retirarmos o ["JobTitlle"] retornará a linha
#inteira do nome em questão

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: object

In [45]:
#Quanto ele recebe incluindo, benefícios?
df[df["EmployeeName"] == "JOSEPH DRISCOLL"] ["TotalPay"]

24    270324.91
Name: TotalPay, dtype: float64

In [46]:
#Quem recebe o maior salário base?
df[df["BasePay"] == df["BasePay"].max()]

#selecionaei a linha seguida de seu valor máximo

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
72925,72926,Gregory P Suhr,Chief of Police,319275.01,0.0,20007.06,86533.21,339282.07,425815.28,2013,NaN,San Francisco,NaN

In [48]:
#Quem recebe o menor salário?
df["BasePay"].min()

#Ele está devendo para a empresa.Vamos ver esse coitado?

-166.01

In [49]:
#chamando a linha desejada, baseada na coluna "BasePay".
df[df["BasePay"] == df["BasePay"].min()]

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
72832,72833,Irwin Sidharta,Junior Clerk,-166.01,249.02,0.0,6.56,83.01,89.57,2012,NaN,San Francisco,NaN

In [50]:
# Média salarial por ano?
df.groupby("Year")["BasePay"].mean()

Year
2011    63595.956517
2012    65436.406857
2013    69630.030216
2014    66564.421924
Name: BasePay, dtype: float64

In [51]:
# Quantos títulos de trabalho existem?
df["JobTitle"].nunique()

2158

In [52]:
#Quais os títulos?
df["JobTitle"].unique()

# Mostra alguns nomes, pois são muitos.

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ...,
       'Forensic Toxicologist Supervis', 'Conversion', 'Cashier 3'],
      dtype=object)

In [54]:
#Quais os 5 cargos mais comuns?
# a função "value_counts" nos trás os
#valores ordenados por maior quantidade, e em menor no final.
df["JobTitle"].value_counts()#.head(5)
# .head(5) trás somente os 5 mais.

JobTitle
Transit Operator                   7036
Special Nurse                      4389
Registered Nurse                   3736
Public Svc Aide-Public Works       2518
Police Officer 3                   2421
                                   ...
TREE TOPPER SUPERVISOR II             1
TRAINING TECHNICIAN                   1
COURT AD RESOLUTION COORDINATOR       1
ROOFER SUPERVISOR I                   1
POWER PLANT SUPERVISOR I              1
Name: count, Length: 2158, dtype: int64

In [56]:
#Quantas pessoas tem a palavra chefe em seu cargo?
#palavra Chief
# aplicando função em toda coluna "JobTitle"

def chefe(valor):
  if "chief" in valor.lower():#.lower transforma chefe em minúsculo
    return True
  else:
    return False

In [57]:
#aplicando a função aplly

df["JobTitle"].apply(chefe)

0         False
1         False
2         False
3         False
4          True
          ...
148645    False
148647    False
148648    False
148649    False
148653    False
Name: JobTitle, Length: 148650, dtype: bool

In [59]:
#Seleção condicional
df[df["JobTitle"].apply(chefe)]

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.0,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN
5,6,DAVID SULLIVAN,ASSISTANT DEPUTY CHIEF II,118602.00,8601.0,189082.74,NaN,316285.74,316285.74,2011,NaN,San Francisco,NaN
6,7,ALSON LEE,"BATTALION CHIEF, (FIRE DEPARTMENT)",92492.01,89062.9,134426.14,NaN,315981.05,315981.05,2011,NaN,San Francisco,NaN
8,9,MICHAEL MORRIS,"BATTALION CHIEF, (FIRE DEPARTMENT)",176932.64,86362.68,40132.23,NaN,303427.55,303427.55,2011,NaN,San Francisco,NaN
9,10,JOANNE HAYES-WHITE,"CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)",285262.00,0.0,17115.73,NaN,302377.73,302377.73,2011,NaN,San Francisco,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
138011,138012,Sharon C Jackson,Chief Deputy Adlt Probation Of,56660.18,0.00,0.00,566.61,56660.18,57226.79,2014,NaN,San Francisco,PT
139620,139621,Anita S Lee,Chief Clerk,38598.86,0.00,0.00,386.00,38598.86,38984.86,2014,NaN,San Francisco,PT
139709,139710,George D Vaughan,Chief Nursery Specialist,27319.47,483.90,0.00,10334.67,27803.37,38138.04,2014,NaN,San Francisco,PT
140080,140081,Patrick W Gillespie,Chief Preparator,24091.00,0.00,0.00,10176.77,24091.00,34267.77,2014,NaN,San Francisco,PT
140156,140157,Christopher L Ochoa,Chief Stationary Engineer,24392.00,418.71,0.00,8918.44,24810.71,33729.15,2014,NaN,San Francisco,PT